# configs/app.yaml - Main application configuration
api:
  title: "CharaForge T2I Lab"
  description: "Text-to-Image generation and LoRA fine-tuning API"
  version: "0.1.0"
  debug: false

  # Server settings
  host: "0.0.0.0"
  port: 8000
  workers: 4

  # Security
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"

  # Rate limiting
  rate_limit_enabled: true
  rate_limit_per_minute: 60

  # File upload limits
  max_file_size_mb: 50
  allowed_image_types:
    - "image/jpeg"
    - "image/png"
    - "image/webp"

# Cache and storage
cache:
  # AI_CACHE_ROOT will be read from environment
  default_ttl_hours: 24
  cleanup_interval_hours: 6

  # Subdirectories
  models_dir: "models"
  datasets_dir: "datasets"
  outputs_dir: "outputs"
  runs_dir: "runs"

# Default generation settings
generation:
  default_width: 768
  default_height: 768
  default_steps: 25
  default_guidance_scale: 7.5

  # Limits
  max_width: 2048
  max_height: 2048
  max_steps: 150
  min_steps: 1

  # Safety
  safety_check_enabled: true
  nsfw_threshold: 0.5

  # Watermark
  watermark_enabled: true
  watermark_opacity: 0.7
  watermark_position: "bottom-right"

# Training defaults
training:
  # LoRA defaults
  lora:
    default_rank: 16
    default_alpha: 16
    default_learning_rate: 0.0001
    default_batch_size: 1
    default_gradient_accumulation: 8
    default_max_steps: 5000

    # Memory optimization
    mixed_precision: "fp16"
    gradient_checkpointing: true
    use_8bit_optimizer: false

    # Validation
    validation_steps: 500
    save_steps: 500

  # DreamBooth defaults (placeholder)
  dreambooth:
    enabled: false
    default_learning_rate: 0.000002
    prior_preservation: true

# Worker configuration
workers:
  # Queue settings
  default_queue: "generation"
  training_queue: "training"
  batch_queue: "batch"

  # Task limits
  task_soft_time_limit: 3600 # 1 hour
  task_hard_time_limit: 7200 # 2 hours
  max_tasks_per_child: 3

  # Retry policy
  max_retries: 3
  retry_delay: 60

# Monitoring and logging
monitoring:
  enabled: true
  log_level: "INFO"
  log_file: "logs/charaforge.log"

  # Metrics
  collect_metrics: true
  metrics_retention_days: 30

  # Health checks
  health_check_interval: 300 # 5 minutes

# Features flags
features:
  controlnet_enabled: true
  lora_training_enabled: true
  dreambooth_training_enabled: false
  batch_processing_enabled: true
  safety_checks_enabled: true
  watermarking_enabled: true
