# ===== configs/celery/development.yaml =====
# Celery Development Configuration
# 開發環境的 Celery 配置

broker_url: "redis://localhost:6379/0"
result_backend: "redis://localhost:6379/0"

# Worker settings
worker_concurrency: 1
worker_prefetch_multiplier: 1
worker_pool: "solo"  # Windows compatibility

# Task limits
task_soft_time_limit: 1800  # 30 minutes
task_time_limit: 3600       # 1 hour

# Queue routing
task_routes:
  "workers.tasks.training.*":
    queue: "training"
    routing_key: "training"
  "workers.tasks.generation.*":
    queue: "generation"
    routing_key: "generation"
  "workers.tasks.batch.*":
    queue: "batch"
    routing_key: "batch"

# Development specific
worker_send_task_events: true
task_send_sent_event: true
worker_disable_rate_limits: true

# Monitoring
flower:
  port: 5555
  basic_auth: []


# ===== configs/celery/production.yaml =====
# Celery Production Configuration
# 生產環境的 Celery 配置

broker_url: "${REDIS_URL}"
result_backend: "${REDIS_URL}"

# Worker settings
worker_concurrency: 2
worker_prefetch_multiplier: 1
worker_pool: "prefork"

# Task limits
task_soft_time_limit: 3600  # 1 hour
task_time_limit: 7200       # 2 hours

# Queue routing
task_routes:
  "workers.tasks.training.*":
    queue: "training_high_priority"
    routing_key: "training.high"
  "workers.tasks.generation.*":
    queue: "generation_normal"
    routing_key: "generation.normal"
  "workers.tasks.batch.*":
    queue: "batch_low_priority"
    routing_key: "batch.low"

# Production optimizations
task_acks_late: true
task_reject_on_worker_lost: true
result_expires: 3600
result_compression: "gzip"

# Monitoring
worker_send_task_events: true
task_send_sent_event: true
flower:
  port: 5555
  basic_auth: ["admin:${FLOWER_PASSWORD}"]

